version: '3.0'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      - MYSQL_DATABASE=review-chatbot
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=qwerty
      - MYSQL_ROOT_PASSWORD=qwerty
    ports:
      - 3306:3306